### ISSUE TITLE
Example from Short Tutorial doesn't work

### ISSUE THREAD

**Issue by kibi** [aliles/begins#67]
If you try to run the example of use for subcommand:
```
import begin
@begin.subcommand
def name(answer):
    "What is your name?"

@begin.start
def run():
    pass
```

there is the error:

```
Traceback (most recent call last):
  File "C:/Users/asorkin/PycharmProjects/nbackup/test_begins/__init__.py", line 6, in <module>
    @begin.start
  File "C:\Program Files (x86)\Python35-32\lib\site-packages\begin\main.py", line 135, in start
    return _start(func)
  File "C:\Program Files (x86)\Python35-32\lib\site-packages\begin\main.py", line 115, in _start
    prog.start()
  File "C:\Program Files (x86)\Python35-32\lib\site-packages\begin\main.py", line 54, in start
    collector=self._collector)
  File "C:\Program Files (x86)\Python35-32\lib\site-packages\begin\cmdline.py", line 258, in apply_options
    return_value = call_function(subfunc, signature(subfunc), opts)
  File "C:\Program Files (x86)\Python35-32\lib\inspect.py", line 2987, in signature
    return Signature.from_callable(obj, follow_wrapped=follow_wrapped)
  File "C:\Program Files (x86)\Python35-32\lib\inspect.py", line 2737, in from_callable
    follow_wrapper_chains=follow_wrapped)
  File "C:\Program Files (x86)\Python35-32\lib\inspect.py", line 2156, in _signature_from_callable
    raise TypeError('{!r} is not a callable object'.format(obj))
TypeError: None is not a callable object
```

As far as I understand, Begins requires at least one positional parameter set in the main function. I've checked the bug at 0.9 and 0.8 versions.

**Comment by jrbrodie77** [comment]
This bug is related to the python version, I don't get it on Python2.7, but I do get it with Python3.6
