### ISSUE TITLE
kwargs starting with h in @begin.subcommand

### ISSUE THREAD

**Issue by mjdorma** [aliles/begins#7]
This will break cmdline.py when passing the options into the argument parser.

``` python
@begin.subcommand
def world(hello):
    print(hello)

@begin.start
def main():
    pass
```

**Comment by mjdorma** [comment]
Oh, here is the traceback:

``` python
Traceback (most recent call last):
  File "test_fail.py", line 9, in <module>
    def main(eggs=False):
  File "/home/mick/env/begins/local/lib/python2.7/site-packages/begins-0.4-py2.7.egg/begin/main.py", line 108, in start
    return _start(func)
  File "/home/mick/env/begins/local/lib/python2.7/site-packages/begins-0.4-py2.7.egg/begin/main.py", line 88, in _start
    prog= Program(func, **kwargs)
  File "/home/mick/env/begins/local/lib/python2.7/site-packages/begins-0.4-py2.7.egg/begin/main.py", line 21, in __init__
    self._parser = cmdline.create_parser(func, **kwargs)
  File "/home/mick/env/begins/local/lib/python2.7/site-packages/begins-0.4-py2.7.egg/begin/cmdline.py", line 136, in create_parser
    populate_parser(subparser, defaults, funcsig)
  File "/home/mick/env/begins/local/lib/python2.7/site-packages/begins-0.4-py2.7.egg/begin/cmdline.py", line 99, in populate_parser
    '--' + param.name, **args)
  File "/usr/lib/python2.7/argparse.py", line 1295, in add_argument
    return self._add_action(action)
  File "/usr/lib/python2.7/argparse.py", line 1669, in _add_action
    self._optionals._add_action(action)
  File "/usr/lib/python2.7/argparse.py", line 1496, in _add_action
    action = super(_ArgumentGroup, self)._add_action(action)
  File "/usr/lib/python2.7/argparse.py", line 1309, in _add_action
    self._check_conflict(action)
  File "/usr/lib/python2.7/argparse.py", line 1447, in _check_conflict
    conflict_handler(action, confl_optionals)
  File "/usr/lib/python2.7/argparse.py", line 1454, in _handle_conflict_error
    raise ArgumentError(action, message % conflict_string)
argparse.ArgumentError: argument -h/--help: conflicting option string(s): -h
(begins)mick@foobar:~/work/begins/tests
```

**Comment by aliles** [comment]
From the traceback I think the subparser is not using the 'resolve' value for conflict resolution. If you would like to try submitting a pull request to fix this issue, try passing `conflict_handler='resolve'` to the `add_subparsers()` method.
